-- MySQL Script generated by MySQL Workbench
-- Sun Aug 25 16:41:42 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema azteca
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `azteca` ;

-- -----------------------------------------------------
-- Schema azteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `azteca` DEFAULT CHARACTER SET utf8 ;
USE `azteca` ;

-- -----------------------------------------------------
-- Table `azteca`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `azteca`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `azteca`.`Cliente` (
  `idCliente` DECIMAL NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `ApPaterno` VARCHAR(25) NULL,
  `ApMaterno` VARCHAR(25) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `azteca`.`PerfilCompra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `azteca`.`PerfilCompra` ;

CREATE TABLE IF NOT EXISTS `azteca`.`PerfilCompra` (
  `idPerfilCompra` INT NOT NULL,
  `MontoMax` DECIMAL NULL,
  `CatalogoEntidiades_idCatalogoEntidiades` INT NOT NULL,
  `HorarioMin` TIME NOT NULL,
  `HorarioMax` TIME NOT NULL,
  PRIMARY KEY (`idPerfilCompra`, `CatalogoEntidiades_idCatalogoEntidiades`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `azteca`.`Cuenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `azteca`.`Cuenta` ;

CREATE TABLE IF NOT EXISTS `azteca`.`Cuenta` (
  `idCuenta` DECIMAL NOT NULL,
  `NumTarjeta` VARCHAR(45) NOT NULL,
  `FechaEmision` VARCHAR(5) NULL,
  `FechaVencimiento` VARCHAR(5) NULL,
  `Debito` INT NULL,
  `Cliente_idCliente` DECIMAL NOT NULL,
  `PerfilCompra_idPerfilCompra` INT NOT NULL,
  `PerfilCompra_CatalogoEntidiades_idCatalogoEntidiades` INT NOT NULL,
  PRIMARY KEY (`idCuenta`, `NumTarjeta`),
  INDEX `fk_Cuenta_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Cuenta_PerfilCompra1_idx` (`PerfilCompra_idPerfilCompra` ASC, `PerfilCompra_CatalogoEntidiades_idCatalogoEntidiades` ASC) VISIBLE,
  CONSTRAINT `fk_Cuenta_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `azteca`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cuenta_PerfilCompra1`
    FOREIGN KEY (`PerfilCompra_idPerfilCompra` , `PerfilCompra_CatalogoEntidiades_idCatalogoEntidiades`)
    REFERENCES `azteca`.`PerfilCompra` (`idPerfilCompra` , `CatalogoEntidiades_idCatalogoEntidiades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `azteca`.`CatalogoEntidiades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `azteca`.`CatalogoEntidiades` ;

CREATE TABLE IF NOT EXISTS `azteca`.`CatalogoEntidiades` (
  `idCatalogoEntidiades` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `dominio` VARCHAR(45) NOT NULL,
  `PerfilCompra_idPerfilCompra` INT NOT NULL,
  `PerfilCompra_CatalogoEntidiades_idCatalogoEntidiades` INT NOT NULL,
  PRIMARY KEY (`idCatalogoEntidiades`),
  UNIQUE INDEX `dominio_UNIQUE` (`dominio` ASC) VISIBLE,
  INDEX `fk_CatalogoEntidiades_PerfilCompra1_idx` (`PerfilCompra_idPerfilCompra` ASC, `PerfilCompra_CatalogoEntidiades_idCatalogoEntidiades` ASC) VISIBLE,
  CONSTRAINT `fk_CatalogoEntidiades_PerfilCompra1`
    FOREIGN KEY (`PerfilCompra_idPerfilCompra` , `PerfilCompra_CatalogoEntidiades_idCatalogoEntidiades`)
    REFERENCES `azteca`.`PerfilCompra` (`idPerfilCompra` , `CatalogoEntidiades_idCatalogoEntidiades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
